//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlPanel.Resources.Global", typeof(Global).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active services.
        /// </summary>
        public static string Active_services {
            get {
                return ResourceManager.GetString("Active_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Path.
        /// </summary>
        public static string Add_path {
            get {
                return ResourceManager.GetString("Add_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add service.
        /// </summary>
        public static string Add_service {
            get {
                return ResourceManager.GetString("Add_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Message.
        /// </summary>
        public static string AddNewMessage {
            get {
                return ResourceManager.GetString("AddNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Ratio.
        /// </summary>
        public static string AddNewRatio {
            get {
                return ResourceManager.GetString("AddNewRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All services.
        /// </summary>
        public static string All_services {
            get {
                return ResourceManager.GetString("All_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        public static string All_Users {
            get {
                return ResourceManager.GetString("All_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg Services In One Day.
        /// </summary>
        public static string AvgServicesInOneDay {
            get {
                return ResourceManager.GetString("AvgServicesInOneDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Ratio.
        /// </summary>
        public static string BalanceRatio {
            get {
                return ResourceManager.GetString("BalanceRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIC FUNCTIONS.
        /// </summary>
        public static string BASIC_FUNCTIONS {
            get {
                return ResourceManager.GetString("BASIC_FUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us Messages.
        /// </summary>
        public static string Contact_us {
            get {
                return ResourceManager.GetString("Contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Users.
        /// </summary>
        public static string DeletedUsers {
            get {
                return ResourceManager.GetString("DeletedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done services.
        /// </summary>
        public static string Done_services {
            get {
                return ResourceManager.GetString("Done_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Active Services.
        /// </summary>
        public static string NumberOfActiveServices {
            get {
                return ResourceManager.GetString("NumberOfActiveServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Done Services.
        /// </summary>
        public static string NumberOfDoneServices {
            get {
                return ResourceManager.GetString("NumberOfDoneServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Users.
        /// </summary>
        public static string OnlineUsers {
            get {
                return ResourceManager.GetString("OnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string Payments {
            get {
                return ResourceManager.GetString("Payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presonal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhoneNumber.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        public static string Ratings {
            get {
                return ResourceManager.GetString("Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio For Each Path.
        /// </summary>
        public static string RatioForEachPath {
            get {
                return ResourceManager.GetString("RatioForEachPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service Paths.
        /// </summary>
        public static string service_Paths {
            get {
                return ResourceManager.GetString("service_Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service_PathsInformation.
        /// </summary>
        public static string service_PathsInformation {
            get {
                return ResourceManager.GetString("service_PathsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service providerList.
        /// </summary>
        public static string service_provider_List {
            get {
                return ResourceManager.GetString("service_provider_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service provider.
        /// </summary>
        public static string ServiceProvider {
            get {
                return ResourceManager.GetString("ServiceProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Providers.
        /// </summary>
        public static string ServiceProviders {
            get {
                return ResourceManager.GetString("ServiceProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to services.
        /// </summary>
        public static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Parameters.
        /// </summary>
        public static string SystemParameters {
            get {
                return ResourceManager.GetString("SystemParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Parameters Information.
        /// </summary>
        public static string SystemParametersInformation {
            get {
                return ResourceManager.GetString("SystemParametersInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string User_List {
            get {
                return ResourceManager.GetString("User_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string User_List_All {
            get {
                return ResourceManager.GetString("User_List_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Works.
        /// </summary>
        public static string UserWorks {
            get {
                return ResourceManager.GetString("UserWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
