namespace fsrhilmakv2.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class priziesUPdate : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.CompetitionPrizes", "CompetitionId", "dbo.Competitions");
            DropIndex("dbo.CompetitionPrizes", new[] { "CompetitionId" });
            AddColumn("dbo.CompetitionPrizes", "rank1", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank2", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank3", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank4", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank5", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank6", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank7", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank8", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank9", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank10", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank11", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank12", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank13", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank14", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank15", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank16", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank17", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank18", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank19", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank20", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank21", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank22", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank23", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank24", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank25", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank26", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank27", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank28", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank29", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank30", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank31", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank32", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank33", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank34", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank35", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank36", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank37", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank38", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank39", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank40", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank41", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank42", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank43", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank44", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank45", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank46", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank47", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank48", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank49", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank50", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank51", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank52", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank53", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank54", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank55", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank56", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank57", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank58", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank59", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank60", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank61", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank62", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank63", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank64", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank65", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank66", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank67", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank68", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank69", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank70", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank71", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank72", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank73", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank74", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank75", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank76", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank77", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank78", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank79", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank80", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank81", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank82", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank83", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank84", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank85", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank86", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank87", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank88", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank89", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank90", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank91", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank92", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank93", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank94", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank95", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank96", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank97", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank98", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank99", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank100", c => c.Double(nullable: false));
            AddColumn("dbo.Competitions", "prizeId", c => c.Int(nullable: false));
            CreateIndex("dbo.Competitions", "prizeId");
            AddForeignKey("dbo.Competitions", "prizeId", "dbo.CompetitionPrizes", "id", cascadeDelete: true);
            DropColumn("dbo.CompetitionPrizes", "CompetitionId");
            DropColumn("dbo.CompetitionPrizes", "rank");
            DropColumn("dbo.CompetitionPrizes", "price");
        }
        
        public override void Down()
        {
            AddColumn("dbo.CompetitionPrizes", "price", c => c.Double(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "rank", c => c.Int(nullable: false));
            AddColumn("dbo.CompetitionPrizes", "CompetitionId", c => c.Int(nullable: false));
            DropForeignKey("dbo.Competitions", "prizeId", "dbo.CompetitionPrizes");
            DropIndex("dbo.Competitions", new[] { "prizeId" });
            DropColumn("dbo.Competitions", "prizeId");
            DropColumn("dbo.CompetitionPrizes", "rank100");
            DropColumn("dbo.CompetitionPrizes", "rank99");
            DropColumn("dbo.CompetitionPrizes", "rank98");
            DropColumn("dbo.CompetitionPrizes", "rank97");
            DropColumn("dbo.CompetitionPrizes", "rank96");
            DropColumn("dbo.CompetitionPrizes", "rank95");
            DropColumn("dbo.CompetitionPrizes", "rank94");
            DropColumn("dbo.CompetitionPrizes", "rank93");
            DropColumn("dbo.CompetitionPrizes", "rank92");
            DropColumn("dbo.CompetitionPrizes", "rank91");
            DropColumn("dbo.CompetitionPrizes", "rank90");
            DropColumn("dbo.CompetitionPrizes", "rank89");
            DropColumn("dbo.CompetitionPrizes", "rank88");
            DropColumn("dbo.CompetitionPrizes", "rank87");
            DropColumn("dbo.CompetitionPrizes", "rank86");
            DropColumn("dbo.CompetitionPrizes", "rank85");
            DropColumn("dbo.CompetitionPrizes", "rank84");
            DropColumn("dbo.CompetitionPrizes", "rank83");
            DropColumn("dbo.CompetitionPrizes", "rank82");
            DropColumn("dbo.CompetitionPrizes", "rank81");
            DropColumn("dbo.CompetitionPrizes", "rank80");
            DropColumn("dbo.CompetitionPrizes", "rank79");
            DropColumn("dbo.CompetitionPrizes", "rank78");
            DropColumn("dbo.CompetitionPrizes", "rank77");
            DropColumn("dbo.CompetitionPrizes", "rank76");
            DropColumn("dbo.CompetitionPrizes", "rank75");
            DropColumn("dbo.CompetitionPrizes", "rank74");
            DropColumn("dbo.CompetitionPrizes", "rank73");
            DropColumn("dbo.CompetitionPrizes", "rank72");
            DropColumn("dbo.CompetitionPrizes", "rank71");
            DropColumn("dbo.CompetitionPrizes", "rank70");
            DropColumn("dbo.CompetitionPrizes", "rank69");
            DropColumn("dbo.CompetitionPrizes", "rank68");
            DropColumn("dbo.CompetitionPrizes", "rank67");
            DropColumn("dbo.CompetitionPrizes", "rank66");
            DropColumn("dbo.CompetitionPrizes", "rank65");
            DropColumn("dbo.CompetitionPrizes", "rank64");
            DropColumn("dbo.CompetitionPrizes", "rank63");
            DropColumn("dbo.CompetitionPrizes", "rank62");
            DropColumn("dbo.CompetitionPrizes", "rank61");
            DropColumn("dbo.CompetitionPrizes", "rank60");
            DropColumn("dbo.CompetitionPrizes", "rank59");
            DropColumn("dbo.CompetitionPrizes", "rank58");
            DropColumn("dbo.CompetitionPrizes", "rank57");
            DropColumn("dbo.CompetitionPrizes", "rank56");
            DropColumn("dbo.CompetitionPrizes", "rank55");
            DropColumn("dbo.CompetitionPrizes", "rank54");
            DropColumn("dbo.CompetitionPrizes", "rank53");
            DropColumn("dbo.CompetitionPrizes", "rank52");
            DropColumn("dbo.CompetitionPrizes", "rank51");
            DropColumn("dbo.CompetitionPrizes", "rank50");
            DropColumn("dbo.CompetitionPrizes", "rank49");
            DropColumn("dbo.CompetitionPrizes", "rank48");
            DropColumn("dbo.CompetitionPrizes", "rank47");
            DropColumn("dbo.CompetitionPrizes", "rank46");
            DropColumn("dbo.CompetitionPrizes", "rank45");
            DropColumn("dbo.CompetitionPrizes", "rank44");
            DropColumn("dbo.CompetitionPrizes", "rank43");
            DropColumn("dbo.CompetitionPrizes", "rank42");
            DropColumn("dbo.CompetitionPrizes", "rank41");
            DropColumn("dbo.CompetitionPrizes", "rank40");
            DropColumn("dbo.CompetitionPrizes", "rank39");
            DropColumn("dbo.CompetitionPrizes", "rank38");
            DropColumn("dbo.CompetitionPrizes", "rank37");
            DropColumn("dbo.CompetitionPrizes", "rank36");
            DropColumn("dbo.CompetitionPrizes", "rank35");
            DropColumn("dbo.CompetitionPrizes", "rank34");
            DropColumn("dbo.CompetitionPrizes", "rank33");
            DropColumn("dbo.CompetitionPrizes", "rank32");
            DropColumn("dbo.CompetitionPrizes", "rank31");
            DropColumn("dbo.CompetitionPrizes", "rank30");
            DropColumn("dbo.CompetitionPrizes", "rank29");
            DropColumn("dbo.CompetitionPrizes", "rank28");
            DropColumn("dbo.CompetitionPrizes", "rank27");
            DropColumn("dbo.CompetitionPrizes", "rank26");
            DropColumn("dbo.CompetitionPrizes", "rank25");
            DropColumn("dbo.CompetitionPrizes", "rank24");
            DropColumn("dbo.CompetitionPrizes", "rank23");
            DropColumn("dbo.CompetitionPrizes", "rank22");
            DropColumn("dbo.CompetitionPrizes", "rank21");
            DropColumn("dbo.CompetitionPrizes", "rank20");
            DropColumn("dbo.CompetitionPrizes", "rank19");
            DropColumn("dbo.CompetitionPrizes", "rank18");
            DropColumn("dbo.CompetitionPrizes", "rank17");
            DropColumn("dbo.CompetitionPrizes", "rank16");
            DropColumn("dbo.CompetitionPrizes", "rank15");
            DropColumn("dbo.CompetitionPrizes", "rank14");
            DropColumn("dbo.CompetitionPrizes", "rank13");
            DropColumn("dbo.CompetitionPrizes", "rank12");
            DropColumn("dbo.CompetitionPrizes", "rank11");
            DropColumn("dbo.CompetitionPrizes", "rank10");
            DropColumn("dbo.CompetitionPrizes", "rank9");
            DropColumn("dbo.CompetitionPrizes", "rank8");
            DropColumn("dbo.CompetitionPrizes", "rank7");
            DropColumn("dbo.CompetitionPrizes", "rank6");
            DropColumn("dbo.CompetitionPrizes", "rank5");
            DropColumn("dbo.CompetitionPrizes", "rank4");
            DropColumn("dbo.CompetitionPrizes", "rank3");
            DropColumn("dbo.CompetitionPrizes", "rank2");
            DropColumn("dbo.CompetitionPrizes", "rank1");
            CreateIndex("dbo.CompetitionPrizes", "CompetitionId");
            AddForeignKey("dbo.CompetitionPrizes", "CompetitionId", "dbo.Competitions", "id", cascadeDelete: true);
        }
    }
}
